Added metrics reader access to prometheus
redhat-appstudio/infra-deployments pull request #1116
Opened 2023-01-05 14:18 UTC by bamachrn

Signed-off-by: Bama Charan Kundu <bamachrn@gmail.com>

2023-01-05 14:24 UTC, xcoulon requested changes

2023-01-05 14:24 UTC, xcoulon commented on components/monitoring/prometheus/base/configure-prometheus.yaml
> +  creationTimestamp: null
same here

2023-01-05 14:24 UTC, xcoulon commented on components/monitoring/prometheus/base/configure-prometheus.yaml
> +  creationTimestamp: null
same here

2023-01-05 14:56 UTC, xcoulon approved these changes

2023-01-09 09:06 UTC, amfred commented
This'll need a README update if it works.

2023-01-09 09:06 UTC, amfred commented
/lgtm

2023-01-09 09:09 UTC, merged