STONEBLD-40 Add JVM Build Service Dashboard
redhat-appstudio/infra-deployments pull request #1353
Opened 2023-02-16 03:49 UTC by stuartwdouglas

2023-02-16 03:52 UTC, stuartwdouglas commented
Once this is merged https://github.com/redhat-appstudio/jvm-build-service/pull/495 should be merged to keep it in sync

2023-02-17 07:24 UTC, Michkov requested changes
unable to run kustomize

2023-02-17 07:24 UTC, Michkov commented on components/monitoring/grafana/base/jvm-build-service/kustomization.yaml
> +- https://github.com/redhat-appstudio/jvm-build-service/deploy/monitoring/grafana-dashboards/?ref=d02e2a69c094a73b59d5cdf6a6fabef90d44ff9b
```
kustomize build https://github.com/redhat-appstudio/jvm-build-service/deploy/monitoring/grafana-dashboards/?ref=d02e2a69c094a73b59d5cdf6a6fabef90d44ff9b
Error: git cmd = '/usr/bin/git fetch --depth=1 origin d02e2a69c094a73b59d5cdf6a6fabef90d44ff9b': exit status 128
```

2023-02-28 06:39 UTC, Michkov approved these changes

2023-02-28 06:40 UTC, merged