Added external secret for prometheus
redhat-appstudio/infra-deployments pull request #1356
Opened 2023-02-16 11:49 UTC by bamachrn

This PR adds external secrets from vault to prometheus operator

2023-02-16 14:30 UTC, gbenhaim requested changes

2023-02-16 14:30 UTC, gbenhaim commented on components/monitoring/prometheus/stone-stg-m01/monitoring-prometheus-oauth-config-path.yaml
> +- op: add
folder for specific cluster should go under a folder for an environment, for example
`components/gitops/staging/stone-stg-m01/`

2023-02-16 14:33 UTC, gbenhaim commented on components/monitoring/prometheus/base/external-secrets/kustomization.yaml
> +kind: Kustomization
in development, the external-secrets-opeator isn't deployed (at least for now), so I suggest not putting crds it consumes in base.

2023-02-20 13:39 UTC, bamachrn commented
@gbenhaim could you please have a look on this now?

2023-02-20 14:41 UTC, gbenhaim approved these changes

2023-02-20 14:42 UTC, gbenhaim commented
/lgtm

2023-02-20 14:49 UTC, merged