WIP: Expose GH webhook secret to sprayproxy
redhat-appstudio/infra-deployments pull request #1699
Opened 2023-04-20 10:26 UTC by enarha

Sprayproxy will use the secret to validate the webhook request.

2023-04-20 10:28 UTC, enarha commented
This is marked as WIP because External Secrets Operator is still not available on the host clusters.

2023-04-21 05:32 UTC, gbenhaim requested changes
The external-secrets-operator is now available on the hosts clusters.
You would need to also add a secret for staging.
You need need to add the `sprayproxy` to the allow secret of the cluster secret store - https://github.com/redhat-appstudio/infra-deployments/blob/main/components/cluster-secret-store/base/appsre-stonesoup-vault-secret-store.yaml#L29

2023-04-21 19:13 UTC, enarha commented
/retest

2023-04-24 04:31 UTC, gbenhaim approved these changes

2023-04-24 04:32 UTC, merged