chore(STONEO11Y-169): limit login to grafana
redhat-appstudio/infra-deployments pull request #1717
Opened 2023-04-24 13:27 UTC by avi-biton

Limit login to Grafana UI.
Only users with access to 'appstudio-grafana' namespace will get access to Grafana UI.

2023-04-24 13:28 UTC, avi-biton commented
@gbenhaim @alexeykazakov Please review when you can :)

2023-04-25 14:02 UTC, amisstea commented
/test appstudio-e2e-tests

2023-04-25 15:15 UTC, amisstea approved these changes

2023-04-28 14:52 UTC, hmariset approved these changes
LGTM

2023-04-28 14:54 UTC, hmariset commented
/approve

2023-04-30 08:05 UTC, avi-biton commented
/retest

2023-05-01 07:12 UTC, avi-biton commented
/retest

2023-05-01 12:18 UTC, gbenhaim requested changes

2023-05-01 12:18 UTC, gbenhaim commented on components/monitoring/grafana/base/grafana-app.yaml
> +        - '-openshift-sar={"resource": "namespaces", "resourceName": "appstudio-grafana", "namespace": "appstudio-grafana", "verb": "get"}'
I think that we should also add RBAC permissions so RHTAP developers can view Grafana.
You can add it in the `components/authentication/base/everyone-can-view.yaml` file.

2023-05-01 14:06 UTC, gbenhaim commented
/lgtm
/approve

2023-05-01 15:53 UTC, gbenhaim approved these changes

2023-05-01 21:06 UTC, amisstea commented
@avi-biton please clean up the commits and rebase. That may fix the failing e2e tests.

2023-05-03 12:13 UTC, Kousalya1998 approved these changes
/lgtm

2023-05-03 13:20 UTC, merged