HACBS60 - Add support for local cluster rekor
redhat-appstudio/infra-deployments pull request #192
Opened 2022-03-18 15:04 UTC by robnester-rh

This adds support for deploying rekor server in a local cluster.

Signed-off-by: Rob Nester <rnester@redhat.com>

2022-03-18 16:43 UTC, simonbaird commented
/ok-to-test

2022-03-18 16:44 UTC, simonbaird commented
There's an older version of this PR at https://github.com/hacbs-contract/infra-deployments/pull/13 .

2022-03-18 20:37 UTC, simonbaird commented on hack/chains/README.md
> +
It would be nice to mention how to configure chains to use that rekor instance here. I guess it's this:

    ./config rekor-local

2022-03-18 20:38 UTC, simonbaird commented on hack/chains/deploy_local_rekor.sh
> +echo "Done"
Maybe this for some user friendly convenience:

    echo "https://rekor-server.$domain"

2022-03-18 20:40 UTC, simonbaird commented
Not actually related to this PR, but I got this:
```
./config.sh rekor-local
Error: open .items[.spec].spec.rules[.host].host: no such file or directory
```

2022-03-18 20:49 UTC, simonbaird commented
We also need this otherwise chains chokes on the url:

```diff
-    $0 "transparency.url: \"$REKOR_SERVER\"" $2
+    $0 "transparency.url: \"https://$REKOR_SERVER\"" $2
```

2022-03-18 20:50 UTC, simonbaird commented
Sorry, wrong button.

2022-03-18 20:52 UTC, simonbaird commented
I can see chains is trying to post the log entries, but failing with this error:

```
2022-03-18T20:45:44.437Z error [POST /api/v1/log/entries][422] createLogEntry default  &{Code:422 Message:invalid kind value: "hashedrekord"}
2022-03-18T20:45:44.453Z error Returned an error
```

But actually I don't think that's a blocker for this PR. We can file a new bug to track figuring that one out.

2022-03-18 20:54 UTC, simonbaird commented
One nitpick: All the other files are doing the kebab-case rather than the snake_case. If you want to stick with that I don't mind, but consider switching to make it tidier.

2022-03-18 20:56 UTC, simonbaird requested changes
I think it's better to include the two fixups for rekor-local here in this PR. Otherwise lgtm. The argocd went green pretty fast, and it's definitely up and running. Nice patch!

2022-03-18 21:01 UTC, simonbaird commented on hack/chains/deploy_local_rekor.sh
> +echo "Done"
I realized now that `./config.sh rekor-local` shows it to you, I guess it's not too important.

2022-03-18 21:12 UTC, simonbaird commented on hack/chains/README.md
> +
..or maybe the deploy script could just assume you want that and do that for you.

2022-03-18 21:52 UTC, lcarva commented on hack/chains/deploy_local_rekor.tpl
> +    targetRevision: HEAD
Should we pin to a particular version for better reproducibility? I guess the downside is that we won't pick up updates automatically which might be desirable in a dev environment.

2022-03-18 21:52 UTC, lcarva commented on hack/chains/README.md
> +    ./deploy-local-rekor.sh
This file doesn't exist. The one added has `-` instead of `_`.

2022-03-21 14:26 UTC, simonbaird commented
LGTM.

2022-03-21 14:27 UTC, simonbaird commented
I think it's good to merge if prow goes green.

2022-03-21 14:28 UTC, robnester-rh commented on hack/chains/deploy-local-rekor.sh
> +if [[ ! -f $PWD/deploy_local_rekor.tpl ]];then
Fixed.

2022-03-21 14:28 UTC, simonbaird commented
LGTM

2022-03-21 14:59 UTC, merged