chore(RHTAPWATCH-110): Differ uncategorized pipelines and deployments
redhat-appstudio/infra-deployments pull request #1937
Opened 2023-06-12 13:40 UTC by ShakedAviv50313

* Differ between uncategorized pipelines and deployments by adding "label_app_kubernetes_io_managed_by" label to the monitoringstack.

2023-06-13 12:24 UTC, ShakedAviv50313 commented
/retest

2023-06-14 06:18 UTC, ShakedAviv50313 commented
/retest

2023-06-14 06:21 UTC, yftacherzog requested changes
The PR title was changed, but the commit message still tells a different story. Need to change the commit message.

2023-06-14 06:33 UTC, ShakedAviv50313 commented
@yftacherzog Done

2023-06-14 06:34 UTC, yftacherzog commented
/lgtm
/approve

2023-06-14 06:34 UTC, yftacherzog approved these changes

2023-06-14 07:48 UTC, ShakedAviv50313 commented
/retetst

2023-06-14 07:49 UTC, ShakedAviv50313 commented
/retest

2023-06-14 08:17 UTC, avi-biton approved these changes

2023-06-14 12:15 UTC, ShakedAviv50313 commented
/retest

2023-06-15 06:45 UTC, avi-biton commented
/test appstudio-e2e-tests

2023-06-18 07:29 UTC, avi-biton commented
/test appstudio-e2e-tests

2023-06-18 08:35 UTC, ShakedAviv50313 commented
/retest

2023-06-18 08:35 UTC, ShakedAviv50313 commented
@ifireball can you please review this?

2023-06-18 09:24 UTC, ShakedAviv50313 commented
/test appstudio-e2e-tests

2023-06-18 13:39 UTC, ShakedAviv50313 commented
/test appstudio-e2e-tests

2023-06-19 06:37 UTC, ShakedAviv50313 commented
/test appstudio-e2e-tests

2023-06-19 09:02 UTC, yftacherzog commented
/retest-required

2023-06-19 10:22 UTC, yftacherzog commented
/assign @yftacherzog

2023-06-19 10:23 UTC, yftacherzog approved these changes

2023-06-19 10:24 UTC, yftacherzog commented
/approve

2023-06-19 10:26 UTC, yftacherzog commented
/approve

2023-06-19 11:43 UTC, yftacherzog commented
/retest-required

2023-06-19 12:28 UTC, avi-biton commented
/uncc @ifireball

2023-06-19 12:29 UTC, avi-biton commented
/approve

2023-06-19 12:32 UTC, yftacherzog approved these changes

2023-06-19 12:35 UTC, yftacherzog commented
/cc @yftacherzog

2023-06-19 12:35 UTC, yftacherzog commented
/lgtm

2023-06-19 12:35 UTC, yftacherzog approved these changes

2023-06-19 13:01 UTC, yftacherzog commented
/retest-required

2023-06-20 07:17 UTC, ShakedAviv50313 commented
/retest-required

2023-06-20 08:57 UTC, avi-biton commented
/test appstudio-e2e-tests

2023-06-21 07:02 UTC, yftacherzog commented
/retest-required

2023-06-21 08:23 UTC, ShakedAviv50313 commented
/retest-required

2023-06-22 08:59 UTC, avi-biton commented
/test appstudio-e2e-tests

2023-06-22 11:10 UTC, yftacherzog commented
/retest-required

2023-06-25 13:17 UTC, ShakedAviv50313 commented
/retest-required

2023-06-25 16:43 UTC, avi-biton commented
/test appstudio-e2e-tests

2023-06-26 06:43 UTC, yftacherzog commented
/retest-required

2023-06-26 12:22 UTC, yftacherzog commented
/lgtm

2023-06-26 12:23 UTC, yftacherzog commented
/approve

2023-06-26 12:27 UTC, ShakedAviv50313 commented
@avi-biton what did the last commit do? it changed 108 files.

2023-06-26 12:32 UTC, merged