feat(HACBS-2310): add clusterrole for release pipelines
redhat-appstudio/infra-deployments pull request #1983
Opened 2023-06-20 15:09 UTC by johnbieren

Release PipelineRuns need access to Custom Resources in dev and managed namespaces. This commit adds a ClusterRole to provide those permissions. We can then create RoleBindings in the namespaces we need to pull from so that the pipelineruns can access the resources.

2023-06-20 15:27 UTC, scoheb requested changes
role name?

2023-06-20 17:59 UTC, scoheb commented
[FAIL] [e2e-demos-suite] DEVHAS-234: creates an application with springboot component from RHTAP samples [It] waits public component springboot-component pipeline to be finished [e2e-demo]

2023-06-20 17:59 UTC, scoheb commented
not related to the content of this PR

/retest

2023-06-20 18:06 UTC, johnbieren commented
Yeah, Kasem reported that some known issues were affecting e2e today, so I figured it was just due to that (although I admittedly didn't dive in)

2023-06-21 13:20 UTC, scoheb commented
/lgtm

2023-06-21 13:51 UTC, scoheb commented
/lgtm

2023-06-21 14:56 UTC, johnbieren commented
/retest-required

2023-06-21 16:06 UTC, merged