Simplify RBBACs for pipeline-service
redhat-appstudio/infra-deployments pull request #2385
Opened 2023-09-11 16:12 UTC by Roming22

@manish-jangra is trying to sanitize the RBACs in the repository.

I can't recall why we decided to have 2 sets of roles, but at the moment I believe we need just one for the team that grants us access to all tekton related resources, and gives us admin rights on the namespace we manage (so we can restart pods for example).

@sbose78 @jduimovich Please let me know if you do not agree with the content of this PR.

2023-09-11 21:31 UTC, sbose78 approved these changes

2023-09-11 21:36 UTC, sbose78 commented
If its a small group with access, this should suffice.

2023-09-12 03:52 UTC, manish-jangra commented
looks good to me if you want to keep one cluster role 👍

2023-09-12 03:55 UTC, manish-jangra requested changes
need `create` access for tekton resources? Shouldn't that be handled by ArgoCD?

2023-09-12 03:55 UTC, manish-jangra commented on components/pipeline-service/base/rbac/cluster-role/pipeline-service-sre.yaml
>    - create
need `create` access? Shouldn't that be handled by ArgoCD?

2023-09-12 09:13 UTC, manish-jangra commented
/retest-required

2023-09-14 08:33 UTC, manish-jangra commented
/retest-required

2023-09-14 15:45 UTC, manish-jangra commented
/retest-required

2023-09-14 21:04 UTC, sbose78 commented
/lgtm

2023-09-15 01:59 UTC, manish-jangra commented
/retest-required

2023-09-15 04:28 UTC, manish-jangra commented
/retest-required

2023-09-15 13:31 UTC, Roming22 commented
/test appstudio-e2e-tests

2023-09-15 19:01 UTC, Roming22 commented
/test appstudio-e2e-tests

2023-09-15 19:43 UTC, Roming22 commented
/test appstudio-e2e-tests

2023-09-18 06:06 UTC, dheerajodha commented
/test appstudio-e2e-tests

2023-09-18 12:23 UTC, Roming22 commented
/test appstudio-e2e-tests

2023-09-19 06:08 UTC, manish-jangra commented
/retest-required

2023-09-20 12:46 UTC, manish-jangra commented
/lgtm

2023-09-21 09:29 UTC, manish-jangra commented
/lgtm

2023-09-21 15:38 UTC, manish-jangra commented
/lgtm

2023-09-21 15:52 UTC, Roming22 commented
Force merge.

The content has been validated multiple times by now, and there's no reason for it to impact the tests since the changes are non-functional.

2023-09-21 15:53 UTC, merged