RHTAPREL-671: Deploy tenants-config on RH stage
redhat-appstudio/infra-deployments pull request #2735
Opened 2023-11-12 10:17 UTC by gbenhaim

2023-11-13 02:37 UTC, scoheb requested changes
file names

2023-11-13 02:37 UTC, scoheb commented on argo-cd-apps/overlays/staging/kustomization.yaml
> +  - path: tenatns-config-managed.yaml
typo in file name

2023-11-13 02:37 UTC, scoheb commented on argo-cd-apps/overlays/staging/kustomization.yaml
> +  - path: tenatns-config-tenant.yaml
typo in file name

2023-11-23 06:36 UTC, gbenhaim commented on argo-cd-apps/overlays/staging/kustomization.yaml
> +  - path: tenatns-config-tenant.yaml
done

2023-11-23 06:36 UTC, gbenhaim commented on argo-cd-apps/overlays/staging/kustomization.yaml
> +  - path: tenatns-config-managed.yaml
done

2023-11-23 14:12 UTC, scoheb approved these changes

2023-11-27 07:50 UTC, gbenhaim commented
@scoheb it needs lgtm

2023-11-27 11:50 UTC, scoheb approved these changes
/lgtm

2024-01-22 18:59 UTC, arewm commented
@scoheb @gbenhaim, is this PR still needed?

2024-01-22 19:02 UTC, scoheb commented
closing due to inactivity.

2024-01-22 19:02 UTC, closed without merging