[DRAFT] SPI deployment
redhat-appstudio/infra-deployments pull request #29
Opened 2021-11-26 15:28 UTC by skabashnyuk

## Service provider integration deployment 
## Details 
TBD

2021-11-30 13:16 UTC, jduimovich reviewed
The name seems to be in a strange font.  Unclear this is intentional or whether it will even cause issues so this is an FYI  See this
 <img width="549" alt="image" src="https://user-images.githubusercontent.com/7844190/144053828-c040ff4e-6bd3-4768-8962-06edd923cd30.png">

2021-12-01 08:03 UTC, skabashnyuk commented
> The name seems to be in a strange font. Unclear this is intentional or whether it will even cause issues so this is an FYI See this <img alt="image" width="549" src="https://user-images.githubusercontent.com/7844190/144053828-c040ff4e-6bd3-4768-8962-06edd923cd30.png">

@jduimovich I'm still experimenting with vault deployment. After a few tries, I've cleaned up these charts.

2021-12-23 12:32 UTC, skabashnyuk commented
I've added a **draft** mark for this pr. The reason is that this pr has to be reworked in the section of operator deployment. It has to use regular deployment instead of OLM

2021-12-29 09:41 UTC, skabashnyuk commented
/retest

2021-12-30 07:52 UTC, skabashnyuk commented
/retest

2021-12-30 13:03 UTC, skabashnyuk commented
/retest-required

2021-12-30 13:14 UTC, skabashnyuk commented
@sbose78 @jduimovich pr un-drafted and ready to review. The thing that I'm not sure about is about the cert-manager. Maybe it's better to rework it this way https://docs.openshift.com/container-platform/4.6/security/certificates/service-serving-certificate.html#add-service-certificate-validating-webhook_service-serving-certificate

2022-01-04 10:03 UTC, skabashnyuk commented
/retest

2022-01-04 15:04 UTC, sbose78 reviewed
Could you check if you've done the equivalent of https://github.com/redhat-appstudio/application-service/pull/23 ?

2022-01-06 09:16 UTC, skabashnyuk commented
>Could you check if you've done the equivalent of redhat-appstudio/application-service#23 ?

@sbose78 done in https://github.com/redhat-appstudio/service-provider-integration-operator/pull/51

2022-01-06 19:13 UTC, sbose78 commented
Thanks, I will review!

2022-01-06 19:25 UTC, sbose78 requested changes

2022-01-06 19:25 UTC, sbose78 commented on components/spi/kustomization.yaml
> +  - https://github.com/redhat-appstudio/service-provider-integration-operator/config/default?ref=d7a6475c6d948452cdc00941616024c9ef6607cc
We'll need https://github.com/redhat-appstudio/service-provider-integration-operator/commit/4f8d0b4d4e9980518f9a759f7683639e025bc32c ?

2022-01-13 05:04 UTC, sbose78 commented
/retest

2022-01-13 05:04 UTC, sbose78 approved these changes

2022-01-13 07:18 UTC, skabashnyuk commented
/retest

2022-01-13 08:13 UTC, flacatus commented
I see the e2e are failing with an ?unexpected? error in has component:

https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/origin-ci-test/pr-logs/pull/redhat-appstudio_infra-deployments/29/pull-ci-redhat-appstudio-infra-deployments-main-appstudio-e2e-deployment/1481492363904815104/artifacts/appstudio-e2e-deployment/gather-extra/artifacts/pods/application-service_application-service-controller-manager-64bbb845f-rchss_manager.log

2022-01-17 05:38 UTC, merged