konflux(prod): add toolchain host and member OLM configuration
redhat-appstudio/infra-deployments pull request #3342
Opened 2024-02-27 14:39 UTC by mfrancisc

Move the OLM configuration for host and member operator one level up , so that it get's deployed to both Stage and Prod via ArgoCD.

Jira: https://issues.redhat.com/browse/ASC-496

2024-02-27 15:05 UTC, hugares requested changes

2024-02-27 15:05 UTC, hugares commented on components/sandbox/toolchain-host-operator/base/olm/toolchain-host-operator.yaml
You need to remove `- toolchain-host-operator.yaml` from `components/sandbox/toolchain-host-operator/staging/stone-stage-p01/kustomization.yaml`

2024-02-27 15:05 UTC, hugares commented on components/sandbox/toolchain-host-operator/staging/stone-stg-host/toolchain-host-operator.yaml
You need to remove `- toolchain-host-operator.yaml` from `components/sandbox/toolchain-host-operator/staging/stone-stg-host/kustomization.yaml`

2024-02-27 15:11 UTC, mfrancisc commented on components/sandbox/toolchain-host-operator/base/olm/toolchain-host-operator.yaml
done https://github.com/redhat-appstudio/infra-deployments/pull/3342/commits/ef72be689623960190f68bcccc016da3bc7bd57b thanks!

2024-02-27 15:13 UTC, hugares approved these changes
/lgtm

2024-02-27 19:00 UTC, hugares commented
/retest

2024-02-28 10:11 UTC, mfrancisc commented
/test appstudio-e2e-tests

2024-03-01 13:54 UTC, mfrancisc commented
/test appstudio-e2e-tests

2024-03-01 18:56 UTC, hugares commented
/retest

2024-03-03 22:09 UTC, mfrancisc commented
/test appstudio-e2e-tests

2024-03-04 13:27 UTC, mfrancisc commented
Not sure I understand what exactly failed in the e2e tests: https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/test-platform-results/pr-logs/pull/redhat-appstudio_infra-deployments/3342/pull-ci-redhat-appstudio-infra-deployments-main-appstudio-e2e-tests/1764412885297008640/build-log.txt

Seems like registration service deployment get's deleted? 😕

2024-03-05 08:46 UTC, mfrancisc commented
@hugares @dperaza4dustbit I had to rebase , could you PTAL and /lgtm if looks ok ?

2024-03-05 12:42 UTC, hugares commented
/lgtm

2024-03-05 12:50 UTC, dperaza4dustbit approved these changes
/lgtm

2024-03-05 15:04 UTC, mfrancisc commented
/retest

2024-03-05 17:39 UTC, merged