PLNSRVCE-1514: enable results-from sidecar-logs for pipelines
redhat-appstudio/infra-deployments pull request #3562
Opened 2024-04-09 15:06 UTC by jkhelil

2024-04-09 15:16 UTC, jkhelil commented
@lcarva PTAL

2024-04-10 08:27 UTC, jkhelil commented
/retest

2024-04-10 12:31 UTC, jkhelil commented
/retest

2024-04-10 15:09 UTC, gabemontero requested changes
you need to do the development overlay as well @jkhelil ... that is what the e2e's will work off of.

https://github.com/redhat-appstudio/infra-deployments/tree/main/components/pipeline-service/development

there are no associated deploy.yaml's for the development overal

2024-04-10 15:23 UTC, lcarva commented
> you need to do the development overlay as well @jkhelil ... that is what the e2e's will work off of.

Aha! This is why e2e didn't catch errors last time.

2024-04-10 17:33 UTC, gabemontero commented
> > you need to do the development overlay as well @jkhelil ... that is what the e2e's will work off of.
> 
> Aha! This is why e2e didn't catch errors last time.

OMG ... yeah just revisited the original PR and yep it did not bump the dev overlay.  Yikes miss for me.  Should have seen that before.

2024-04-11 11:55 UTC, gabemontero approved these changes
/lgtm

2024-04-11 19:27 UTC, gabemontero commented
/retest

2024-04-12 06:50 UTC, jkhelil commented
/retest

2024-04-12 09:33 UTC, jkhelil commented
Tests are failing, Ci is still failing to provision clusters

2024-04-12 11:48 UTC, jkhelil commented
/retest

2024-04-15 07:48 UTC, jkhelil commented
/retest

2024-04-16 20:58 UTC, gabemontero commented
/hold

/retest

@lcarva will you still do the sanity check on stage-m01 or stage-rh01?  If so, then feel free to release the hold when you are ready, assuming we have green e2e's 

if all good, we'll bump p01 i.e. bifrost cluster and then put this in the queue for prod

2024-04-16 21:17 UTC, lcarva commented
> will you still do the sanity check on stage-m01 or stage-rh01? If so, then feel free to release the hold when you are ready, assuming we have green e2e's

I should be able to test on `stage-m01`. I don't think I have access to create application on `stage-rh01`. If someone triggers the Pipeline that Yash has I can review the results.

2024-04-16 21:19 UTC, gabemontero commented
> > will you still do the sanity check on stage-m01 or stage-rh01? If so, then feel free to release the hold when you are ready, assuming we have green e2e's
> 
> I should be able to test on `stage-m01`. I don't think I have access to create application on `stage-rh01`. If someone triggers the Pipeline that Yash has I can review the results.

I would think m01 is sufficient .... sorry I have no idea how to trigger the pipeline Yash has

2024-05-14 14:50 UTC, gabemontero commented
closing in favor of https://github.com/redhat-appstudio/infra-deployments/pull/3699 with @jkhelil out on PTO and being able to update p01 now

2024-05-14 14:50 UTC, closed without merging