Add pipelines-as-code for enterprise contract
redhat-appstudio/infra-deployments pull request #364
Opened 2022-05-16 12:20 UTC by mbharatk

Tekton is adopted as a primary CI and CD ( images builds ) for enterprise-contract

2022-05-16 12:36 UTC, Michkov requested changes

2022-05-16 12:36 UTC, Michkov commented on components/enterprise-contract/.tekton/serviceaccount.yaml
> +  - name: redhat-appstudio-staginguser-pull-secret
this file is not needed anymore, secrets are handled by sharedsecret.

2022-05-16 12:36 UTC, Michkov commented on components/enterprise-contract/kustomization.yaml
> +- .tekton/
currently no namespace is defined where the resources should be created.

2022-05-16 12:36 UTC, Michkov commented on components/enterprise-contract/.tekton/kustomization.yaml
> +- serviceaccount.yaml
no such file

2022-05-16 12:36 UTC, Michkov commented on components/enterprise-contract/.tekton/kustomization.yaml
> +
Update https://github.com/redhat-appstudio/infra-deployments/blob/main/components/build/shared-resources/shared-resources-components.yaml to allow namespace used by this service to access the secrets.

2022-05-17 13:00 UTC, mbharatk commented
/test appstudio-e2e-deployment

2022-05-17 13:39 UTC, lcarva commented
@mbharatk, I don't quite follow what is being achieved by this PR. Can you explain it to me (in simple terms :smile: ) ?

2022-05-17 14:21 UTC, Michkov commented
@lcarva context -> [PLNSRVCE-270](https://issues.redhat.com/browse/PLNSRVCE-270). We are applying Pipelines-as-code for each repostiory. But in this case it would need some discussion why hacbs-contract is using own repositories instead of redhat-appstudio ones.

2022-05-19 05:20 UTC, mbharatk commented
/test appstudio-e2e-deployment

2022-05-25 06:38 UTC, Michkov approved these changes

2022-05-25 09:59 UTC, zregvart approved these changes
LGTM

2022-05-25 10:02 UTC, merged