chore(KLUXINFRA-743): STAGE: Add "mlarge" platform
redhat-appstudio/infra-deployments pull request #4327
Opened 2024-08-14 05:37 UTC by ifireball

Adding the `linux-mlarge/amd64` platform as a migration path from what was previously called `linux/amd64` as that is being changed to run locally in the cluster.

For completeness sake, also adding `linux-mlarge/arm64` which is identical to the current `linux/arm64` but lets users be explicit about running in a VM.

**This change is only done in STAGE for now**

2024-08-14 08:10 UTC, dheerajodha commented
Sorry, there's a bug in the CI that will be fixed by [this PR](https://github.com/konflux-ci/e2e-tests/pull/1336)
I'll rerun the tests here and on your other PR asap

2024-08-14 10:33 UTC, dheerajodha commented
/test appstudio-e2e-tests

2024-08-14 11:51 UTC, hugares requested changes

2024-08-14 11:51 UTC, hugares commented on components/multi-platform-controller/staging-downstream/host-config.yaml
> +  dynamic.linux-mlarge-arm64.key-name: konflux-stage-ext-mab01
```suggestion
  dynamic.linux-mlarge-arm64.key-name: konflux-stage-int-mab01
```

2024-08-14 11:51 UTC, hugares commented on components/multi-platform-controller/staging-downstream/host-config.yaml
> +  dynamic.linux-mlarge-arm64.security-group-id: sg-05bc8dd0b52158567
```suggestion
  dynamic.linux-mlarge-arm64.security-group-id: sg-0482e8ccae008b240
```

2024-08-14 11:51 UTC, hugares commented on components/multi-platform-controller/staging-downstream/host-config.yaml
> +  dynamic.linux-mlarge-arm64.subnet-id: subnet-030738beb81d3863a
```suggestion
  dynamic.linux-mlarge-arm64.subnet-id: subnet-07597d1edafa2b9d3
```

2024-08-14 11:51 UTC, hugares commented on components/multi-platform-controller/staging-downstream/host-config.yaml
> +  dynamic.linux-mlarge-amd64.subnet-id: subnet-030738beb81d3863a
```suggestion
  dynamic.linux-mlarge-amd64.subnet-id: subnet-07597d1edafa2b9d3
```

2024-08-14 11:51 UTC, hugares commented on components/multi-platform-controller/staging-downstream/host-config.yaml
> +  dynamic.linux-mlarge-amd64.security-group-id: sg-05bc8dd0b52158567
```suggestion
  dynamic.linux-mlarge-amd64.security-group-id: sg-0482e8ccae008b240
```

2024-08-14 11:51 UTC, hugares commented on components/multi-platform-controller/staging-downstream/host-config.yaml
> +  dynamic.linux-mlarge-amd64.key-name: konflux-stage-ext-mab01
```suggestion
  dynamic.linux-mlarge-amd64.key-name: konflux-stage-int-mab01
```

2024-08-15 11:54 UTC, hugares approved these changes
/lgtm

2024-08-15 12:31 UTC, merged