chore(RHTAPWATCH-1267): Update quay repository for project-controller
redhat-appstudio/infra-deployments pull request #4599
Opened 2024-09-25 14:52 UTC by hmariset

Update project-controller quay repository to change to konflux-ci organization from redhat-appstudio.

Jira-Url: https://issues.redhat.com/browse/RHTAPWATCH-1267

2024-09-25 17:27 UTC, amisstea approved these changes
/lgtm

2024-09-26 05:50 UTC, ifireball requested changes
Were the corresponding needed changes made to the project-controller's release pipeline? I haven't seen a PR doing that, nor am I seeing one linked to the Jira issue.

2024-09-26 18:51 UTC, hmariset commented
/retest

2024-09-27 14:39 UTC, hmariset commented
/retest

2024-09-27 17:27 UTC, hmariset commented
/retest

2024-09-30 13:50 UTC, hmariset commented
@ifireball Can you give approval on this PR since the release pipeline changes are already merged.

2024-09-30 15:22 UTC, hmariset commented
/retest-required

2024-09-30 15:55 UTC, hmariset commented
/retest

2024-09-30 23:48 UTC, hmariset commented
/retest

2024-10-01 08:47 UTC, ifireball approved these changes

2024-10-01 08:50 UTC, ifireball requested changes
it seems the PR as it is wouldn't work because the image tag does not exist in quay.io

2024-10-01 08:50 UTC, ifireball commented on components/project-controller/development/kustomization.yaml
>    newTag: 6773b77f353cc019166754ecd4d563035968019c
Need to ensure the tag actually matches a tag we have for this image in quay.io

2024-10-02 14:56 UTC, hmariset commented
/retest

2024-10-02 14:59 UTC, amisstea commented
/lgtm

2024-10-02 15:03 UTC, merged