chore(KFLUXVNGD-128): Delete old crossplane namespace claims
redhat-appstudio/infra-deployments pull request #5094
Opened 2024-12-10 02:12 UTC by hmariset

Delete crossplane namespace claims periodically to prevent the compute provided.

Jira-Url: https://issues.redhat.com/browse/KFLUXVNGD-128

2024-12-10 14:47 UTC, amisstea requested changes
Why do we need another component for this? I was thinking this CronJob and its config could reside in `crossplane-control-plane` since it's a tightly coupled dependency.

2024-12-10 14:47 UTC, amisstea commented on components/namespace-claim-cleaner/base/rbac.yaml
> +      - delete
This isn't a valid resource nor should this role/SA interact with anything related to the toolchain operators. Please remove this.

2024-12-10 14:47 UTC, amisstea commented on components/namespace-claim-cleaner/base/rbac.yaml
> +      - list
We shouldn't need to list core namespaces. We need to be able to list and delete namespace in the `eaas.konflux-ci-dev` api group.

2024-12-10 14:47 UTC, amisstea commented on components/namespace-claim-cleaner/base/namespace-claim-configmap.yaml
> +    LABEL="namespaces.eaas.konflux-ci-dev"
We can't list the namespaces generated by the claim. They're not available on the cluster where this code runs.

This is more complex that it needs to be. We want to list and delete the stale `namespaces.eaas.konflux-ci-dev` resources.

2024-12-16 17:34 UTC, amisstea reviewed
@hmariset please include some evidence showing how this was tested in a dev cluster with it successfully cleaning up stale namespace claims while ignoring others.

2024-12-16 17:34 UTC, amisstea commented on components/crossplane-control-plane/base/cronjob.yaml
> +              image: bitnami/kubectl:latest
We shouldn't use `docker.io` due to security risks and rate limiting issues. Pulling the `latest` tag is also generally ill advised for production code - we should pull by a more specific tag and digest whenever possible. Please use the [appstudio-utils](https://quay.io/repository/konflux-ci/appstudio-utils?tab=tags) image instead which has `kubectl` and `jq`/`yq` baked in.

2024-12-16 17:34 UTC, amisstea commented on components/crossplane-control-plane/base/namespace-claim-configmap.yaml
> +      CREATION_TIMESTAMP=$(echo $claim | jq -r '.metadata.creationTimestamp')
No pipeline required (untested but should work):
```suggestion
      CREATION_TIMESTAMP=$(jq -r '.metadata.creationTimestamp' <<< "$claim")
```

2024-12-16 17:34 UTC, amisstea commented on components/crossplane-control-plane/base/namespace-claim-configmap.yaml
> +        NAME=$(echo $claim | jq -r '.metadata.name')
```suggestion
        NAME=$(jq -r '.metadata.name' <<< "$claim")
```

2024-12-16 17:34 UTC, amisstea commented on components/crossplane-control-plane/base/namespace-claim-configmap.yaml
> +      if [ $AGE -gt (2*24*3600) ]; then
This is checking if the claim is older than 2 days, right? If so, why so long?

2024-12-16 17:34 UTC, amisstea commented on components/crossplane-control-plane/base/namespace-claim-configmap.yaml
> +    #!/bin/bash
Is this going to fail properly if any of the piped commands below fail? I suspect it won't without `set`ting some options.

2024-12-18 21:04 UTC, amisstea commented on components/crossplane-control-plane/base/kustomization.yaml
> +- namespace-claim-configmap.yaml
Nit: be consistent with filenames & resource names.
```suggestion
- configmap.yaml
```

2024-12-18 21:11 UTC, hmariset commented
![image](https://github.com/user-attachments/assets/89e15204-a1ae-4ee8-9de7-d94177243cf8)
Successfully deleted "my-namespace" in "test-pvc".

2024-12-18 21:12 UTC, hmariset commented
![image](https://github.com/user-attachments/assets/aae93f58-5aea-4870-a8f5-e5805c5e210f)
When there are no namespaces.eaas.konflux-ci.dev resources.

2024-12-18 21:16 UTC, hmariset commented
To create sample `namespaces.eaas.konflux-ci.dev` object you can use the example from [`crossplane-control-plane`](https://github.com/konflux-ci/crossplane-control-plane/blob/main/examples/xnamespace/claim.yaml) repo.
`kubectl apply -f examples/xnamespace/claim.yaml`

2024-12-18 21:22 UTC, hmariset commented on components/crossplane-control-plane/base/namespace-claim-configmap.yaml
> +  name: namespace-claim-configmap
Updated.

2024-12-18 21:33 UTC, amisstea approved these changes
/lgtm

2024-12-18 22:14 UTC, merged