add kyverno to staging
redhat-appstudio/infra-deployments pull request #5203
Opened 2024-12-20 17:34 UTC by sadlerap

Kyverno policies will be added in a future PR.

2025-01-06 18:14 UTC, dperaza4dustbit approved these changes
/lgtm

2025-01-07 10:20 UTC, filariow requested changes
some ArgoCD related changes

2025-01-07 10:20 UTC, filariow commented on argo-cd-apps/base/member/infra-deployments/kyverno/kyverno.yaml
> +          targetRevision: 1.13
It seems to me this value should be the ChartVersion

cf. https://github.com/kyverno/kyverno/tree/release-1.13/charts/kyverno#installing-the-chart

```suggestion
          targetRevision: 3.3.4
```

2025-01-07 22:21 UTC, sadlerap commented on argo-cd-apps/base/member/infra-deployments/kyverno/kyverno.yaml
Fixed in ed5b5232.

Do you know where the configmap is controlled or if it can be overridden by infra-deployments?  I see an owner reference to argocd on the live versions of it (probably from the helm chart behind openshift-gitops), but I don't find a reference to it in this repository.

2025-01-07 22:22 UTC, sadlerap commented on argo-cd-apps/base/member/infra-deployments/kyverno/kyverno.yaml
> +          targetRevision: 1.13
Fixed in ed5b523.

2025-01-08 10:46 UTC, filariow commented on argo-cd-apps/base/member/infra-deployments/kyverno/kyverno.yaml
I'm not sure about it. @hugares @manish-jangra @bamachrn can you help here?

2025-01-08 18:19 UTC, dperaza4dustbit approved these changes
/lgtm

2025-01-08 18:32 UTC, amisstea commented on argo-cd-apps/base/member/infra-deployments/kyverno/kyverno.yaml
@filariow @sadlerap the configs are store on the internal gitlab and they utilize the `ArgoCD` custom resource. See:

- [argocd-stage.yml](https://gitlab.cee.redhat.com/service/app-interface/-/blob/master/resources/stonesoup/argocd-control-plane/argocd-stage.yml)
- [argocd.yaml](https://gitlab.cee.redhat.com/service/app-interface/-/blob/master/resources/stonesoup/argocd-control-plane/argocd.yml)

2025-01-10 17:14 UTC, sadlerap commented on argo-cd-apps/base/member/infra-deployments/kyverno/kyverno.yaml
Filed https://gitlab.cee.redhat.com/service/app-interface/-/merge_requests/129507 for staging, will file a separate MR for prod.  Local testing by both @filariow and myself seemed to indicate that this will be safe to add, even to clusters that won't have kyverno installed.

I didn't come across a way to do resource exclusions on a per-application basis.

2025-01-10 19:12 UTC, filariow approved these changes
/lgtm

2025-01-13 18:52 UTC, hugares approved these changes

2025-01-13 19:07 UTC, hugares commented on argo-cd-apps/base/member/infra-deployments/kyverno/kyverno.yaml
@filariow change in argocd is in, can we resolve this conversation?

2025-01-13 19:39 UTC, filariow commented on argo-cd-apps/base/member/infra-deployments/kyverno/kyverno.yaml
Sure, I'll do it

2025-01-13 20:52 UTC, merged