Add permission claim for ApplicationSnapshots to HAS APIExports
redhat-appstudio/infra-deployments pull request #880
Opened 2022-10-31 19:38 UTC by johnmcollier

See https://issues.redhat.com/browse/DEVHAS-188

It appears the APIExports for HAS were missing the permissionclaim for the ApplicationSnapshot resource, so this PR adds it to all of the necessary APIExports for HAS in infra-deployments.

In my testing, I also noticed that KCP had issues handling APIExports that had updated permission claims:
```
    message: '1 unexpected and/or invalid permission claims (showing first 1): unexpected/invalid
      claim for applicationsnapshots.appstudio.redhat.com (identity "06dfd2f7d69f251dc79489f4438adc0efdff59c2ed27ae5f09ccd778319e6993")'
```

So a delete & re-create of the modified APIExports may be required for these changes to take effect.

2022-10-31 19:39 UTC, johnmcollier commented
@Michkov Do you mind reviewing this when you get the chance? Thanks!

2022-10-31 20:27 UTC, johnmcollier commented
/retest

2022-10-31 21:39 UTC, johnmcollier commented
/retest

2022-10-31 23:37 UTC, johnmcollier commented
/retest

2022-11-01 07:32 UTC, Michkov requested changes
This process is automated :smile: , the changes are already included in #862, this PR can be closed.

2022-11-04 08:15 UTC, closed without merging